init:
  - git config --global core.autocrlf input
before_build:
  - nuget restore .\Octokit.SpiApi.sln
environment:
  access_token:
    secure: cyvLxdGBSCXY+0B/xaUKTvmFYn8ji/BfI721QMWN5PDnZ57mMPDrIY9qVivwhlhT
  git_user: mminns-agent
  git_email: mminns-agent@appveyor.com
  git_repo: https://github.com/mminns/octokit.net.git
build_script:
  - cmd: build.spiapi.cmd BuildApp
  - cmd: build.spiapi.cmd UnitTests
  - cmd: build.spiapi.cmd CreatePackages
test: off
on_success:
  - ps: |
		git config --global credential.helper store
		git config --global user.email $env:git_email
		git config --global user.name $env:git_user
		git config --global push.default simple
		git remote add octokit-mminns https://github.com/mminns/octokit.net.git
		Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
		git add . -u
		git commit -m "Successful CI Build:$env:APPVEYOR_BUILD_NUMBER"
		git tag "ci-build-$env:APPVEYOR_BUILD_NUMBER"
		git push octokit-mminns spiapi
		git push octokit-mminns spiapi --tags